export const UserStatus = {
    UNKNOWN: -1,
    GUEST: 0,
    LOGGED_IN: 10,
    UNVERIFIED: 30,
    MISSING_ATTRIBUTES: 50,
    BILLING_INFORMATION_NEEDED: 70,
    INVALID_BILLING_INFORMATION: 80,
    FULLY_APPROVED: 100,
}