export const language_keys = {
    afr: "Afrikaans",
    amh: "Amharic",
    ara: "Arabic",
    asm: "Assamese",
    aze_cyrl: "Azerbaijani Cyrillic",
    aze: "Azerbaijani",
    bel: "Belarusian",
    ben: "Bengali",
    bod: "Tibetan",
    bos: "Bosnian",
    bre: "Breton",
    bul: "Bulgarian",
    cat: "Catalan",
    ceb: "Cebuano",
    ces: "Czech",
    chi_sim: "Chinese Simplified",
    chi_tra: "Chinese Traditional",
    chr: "Cherokee",
    cos: "Corsican",
    cym: "Welsh",
    dan_frak: "Danish Fraktur",
    dan: "Danish",
    deu_frak: "German Fraktur",
    deu: "German",
    div: "Divehi",
    dzo: "Dzongkha",
    ell: "Greek",
    eng: "English",
    enm: "English, Middle (1100-1500)",
    epo: "Esperanto",
    equ: "Math/Equations",
    est: "Estonian",
    eus: "Basque",
    fao: "Faroese",
    fas: "Persian",
    fil: "Filipino",
    fin: "Finnish",
    fra: "French",
    frk: "Frankish",
    fry: "Frisian",
    gla: "Scottish Gaelic",
    gle: "Irish",
    glg: "Galician",
    guj: "Gujarati",
    hat: "Haitian Creole",
    heb: "Hebrew",
    hin: "Hindi",
    hrv: "Croatian",
    hun: "Hungarian",
    hye: "Armenian",
    iku: "Inuktitut",
    ind: "Indonesian",
    isl: "Icelandic",
    ita: "Italian",
    jav: "Javanese",
    jpn: "Japanese",
    kan: "Kannada",
    kat: "Georgian",
    kaz: "Kazakh",
    khm: "Khmer",
    kir: "Kyrgyz",
    kmr: "Northern Kurdish",
    kor: "Korean",
    lao: "Lao",
    lat: "Latin",
    lav: "Latvian",
    lit: "Lithuanian",
    ltz: "Luxembourgish",
    mal: "Malayalam",
    mar: "Marathi",
    mkd: "Macedonian",
    mlt: "Maltese",
    mon: "Mongolian",
    mri: "Maori",
    msa: "Malay",
    mya: "Burmese",
    nep: "Nepali",
    nld: "Dutch",
    nor: "Norwegian",
    ori: "Oriya",
    pan: "Punjabi",
    pol: "Polish",
    por: "Portuguese",
    pus: "Pashto",
    que: "Quechua",
    ron: "Romanian",
    rus: "Russian",
    san: "Sanskrit",
    sin: "Sinhalese",
    slk_frak: "Slovak Fraktur",
    slk: "Slovak",
    slv: "Slovenian",
    snd: "Sindhi",
    spa_old: "Spanish Old",
    spa: "Spanish",
    sqi: "Albanian",
    srp_latn: "Serbian Latin",
    srp: "Serbian",
    sun: "Sundanese",
    swa: "Swahili",
    swe: "Swedish",
    syr: "Syriac",
    tam: "Tamil",
    tat: "Tatar",
    tel: "Telugu",
    tgk: "Tajik",
    tgl: "Tagalog",
    tha: "Thai",
    tir: "Tigrinya",
    ton: "Tongan",
    tur: "Turkish",
    uig: "Uighur",
    ukr: "Ukrainian",
    urd: "Urdu",
    uzb_cyrl: "Uzbek Cyrillic",
    uzb: "Uzbek",
    vie: "Vietnamese",
    yid: "Yiddish",
    yor: "Yoruba",
};